### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/pyswarms#154]
**Documentation Task-List**

- [x] RST file for Inverse Kinematics 
- [x] Add citiation in the `Pyramid` topology to [this paper](http://pubs.cs.uct.ac.za/archive/00000477/01/ParticleSwarm.pdf)
- [x] Use command style in the doc string's "subject line"(PEP257)
- [x] Update documentation and docstrings using http://www.hemingwayapp.com/ (Readability ~Grade 9)
- [x] Merge (file merge, not git merge! :laughing: ) `basic_optimization` example with `**kwargs` example (add RST file too)
- [x] Note on large boundaries, etc. (see #152)
- [x] Note on precision and overflow (see #152)
- [x] Note on creating custom-objective function (return value should be `(n_particles)` see #109 )
- [ ] Update `README` (put Siobhan and Aaron as Collaborators).

**Comment by whzup** [comment]
What do you think about adding [PEP257 conformity](https://www.python.org/dev/peps/pep-0257/), @ljvmiranda921?

**Comment by ljvmiranda921** [comment]
I think our [numpydoc convention](https://github.com/numpy/numpydoc) for the docstrings is already good :smile: I find it easier to read and parse. Although I am not sure if we are talking about the same thing. Which parts do we need PEP 257-compliance?

**Comment by whzup** [comment]
Ok, I see. Just learned about PEP257 and thought we may use it 😄. I was especially wondering about this note:

> The docstring is a phrase ending in a period. It prescribes the function or method's effect as a command ("Do this", "Return that"), not as a description; e.g. don't write "Returns the pathname ...".

It's the same as in the commit message subject line. I don't see the point in doing so, both variants seem fine to me but maybe you know why one would do that?

By the way, I try to make this repository more welcoming for first-timers. This has only partly to do with documentation. I found some nice sources for this to happen. Shall I open an issue where we can discuss this further?

**Comment by ljvmiranda921** [comment]
Interesting. Okay, I'll add it on the checklist. 

Cool! Wanna discuss on gitter first?

**Comment by ljvmiranda921** [comment]
> It's the same as in the commit message subject line. I don't see the point in doing so, both variants seem fine to me but maybe you know why one would do that?

Interesting, okay, you can add it on the checklist.

> Shall I open an issue where we can discuss this further?

Hmmm... wanna discuss this first on gitter?

**Comment by whzup** [comment]
We should run `flake8` once more before release 😄. Don't know if this belongs here, though. I don't know what some things do that `flake8` wants to be changed so I'd rather give this to someone who knows what he's doing there 😆.
